package mcp

import "github.com/mark3labs/mcp-go/mcp"

// toolDefs returns the static MCP tool definitions for all 8 Joe tools.
// Tools are category-based: callers describe *what* they want, not *how* to query a specific backend.
// joe-core resolves the backend, translates the question, executes, and returns normalized results.
func toolDefs() []mcp.Tool {
	return []mcp.Tool{
		mcp.NewTool("joe_graph_query",
			mcp.WithDescription("Search Joe's infrastructure graph for nodes matching a query string. Returns matching nodes with their type, labels, and metadata."),
			mcp.WithString("query",
				mcp.Description("Search query (e.g. 'payment-svc', 'prod', 'postgres')"),
				mcp.Required(),
			),
		),
		mcp.NewTool("joe_graph_related",
			mcp.WithDescription("Find infrastructure nodes related to a given node ID within a specified depth. Useful for understanding dependencies and relationships."),
			mcp.WithString("node_id",
				mcp.Description("The node ID to find related nodes for (e.g. 'service:payment-svc')"),
				mcp.Required(),
			),
			mcp.WithNumber("depth",
				mcp.Description("Traversal depth (1-3, default 1)"),
				mcp.DefaultNumber(1),
			),
		),
		mcp.NewTool("joe_k8s",
			mcp.WithDescription("Answer a Kubernetes question about a service. Joe resolves the cluster from the graph and returns pods, deployments, or logs depending on the question."),
			mcp.WithString("service",
				mcp.Description("Service name (e.g. 'payment-svc')"),
				mcp.Required(),
			),
			mcp.WithString("question",
				mcp.Description("Natural language question (e.g. 'show me the running pods', 'get the last 100 log lines')"),
				mcp.Required(),
			),
		),
		mcp.NewTool("joe_metrics",
			mcp.WithDescription("Query metrics for a service. Joe resolves the metrics backend (Prometheus, Datadog, Dynatrace, New Relic) from the graph, translates the question into the appropriate query language, and returns results."),
			mcp.WithString("service",
				mcp.Description("Service name (e.g. 'payment-svc')"),
				mcp.Required(),
			),
			mcp.WithString("question",
				mcp.Description("Natural language question (e.g. 'p99 latency over the last 10 minutes', 'request rate', 'error rate')"),
				mcp.Required(),
			),
		),
		mcp.NewTool("joe_logs",
			mcp.WithDescription("Search logs for a service. Joe resolves the log backend (Loki, Datadog, Splunk) from the graph, translates the question into the appropriate query, and returns results."),
			mcp.WithString("service",
				mcp.Description("Service name (e.g. 'payment-svc')"),
				mcp.Required(),
			),
			mcp.WithString("question",
				mcp.Description("Natural language question (e.g. 'errors in the last hour', 'timeout messages today')"),
				mcp.Required(),
			),
		),
		mcp.NewTool("joe_traces",
			mcp.WithDescription("Find recent traces for a service. Joe resolves the tracing backend (Tempo, Jaeger) from the graph and returns trace search results."),
			mcp.WithString("service",
				mcp.Description("Service name (e.g. 'payment-svc')"),
				mcp.Required(),
			),
			mcp.WithString("question",
				mcp.Description("Natural language question (e.g. 'slow traces in the last 30 minutes', 'failed checkout requests')"),
				mcp.Required(),
			),
		),
		mcp.NewTool("joe_alerts",
			mcp.WithDescription("List active alerts for a service. Joe resolves the alerting backend (Alertmanager, PagerDuty) from the graph and returns firing/acknowledged alerts."),
			mcp.WithString("service",
				mcp.Description("Service name (e.g. 'payment-svc')"),
				mcp.Required(),
			),
			mcp.WithString("question",
				mcp.Description("Optional filter hint (e.g. 'critical only', 'severity=warning') — passed to the alerting backend as a filter"),
			),
		),
		mcp.NewTool("joe_knowledge_search",
			mcp.WithDescription("Semantic search over Joe's knowledge store — runbooks, wiki pages, and learned operational patterns."),
			mcp.WithString("query",
				mcp.Description("Natural language query (e.g. 'payment service database connection errors')"),
				mcp.Required(),
			),
			mcp.WithNumber("top_k",
				mcp.Description("Maximum number of results to return (default 5)"),
				mcp.DefaultNumber(5),
			),
		),
	}
}
