package mcp

import "github.com/mark3labs/mcp-go/mcp"

// toolDefs returns the static MCP tool definitions for all 8 Joe tools.
func toolDefs() []mcp.Tool {
	return []mcp.Tool{
		mcp.NewTool("joe_graph_query",
			mcp.WithDescription("Search Joe's infrastructure graph for nodes matching a query string. Returns matching nodes with their type, labels, and metadata."),
			mcp.WithString("query",
				mcp.Description("Search query (e.g. 'payment-svc', 'prod', 'postgres')"),
				mcp.Required(),
			),
		),
		mcp.NewTool("joe_graph_related",
			mcp.WithDescription("Find infrastructure nodes related to a given node ID within a specified depth. Useful for understanding dependencies and relationships."),
			mcp.WithString("node_id",
				mcp.Description("The node ID to find related nodes for (e.g. 'service:payment-svc')"),
				mcp.Required(),
			),
			mcp.WithNumber("depth",
				mcp.Description("Traversal depth (1-3, default 1)"),
				mcp.DefaultNumber(1),
			),
		),
		mcp.NewTool("joe_k8s_get",
			mcp.WithDescription("Get Kubernetes resources from a connected cluster. Supports listing or getting a specific resource."),
			mcp.WithString("source_id",
				mcp.Description("The Kubernetes source ID from Joe's source registry"),
				mcp.Required(),
			),
			mcp.WithString("resource",
				mcp.Description("Resource type (e.g. 'pods', 'deployments', 'services', 'nodes')"),
				mcp.Required(),
			),
			mcp.WithString("namespace",
				mcp.Description("Kubernetes namespace (empty for cluster-scoped resources)"),
			),
			mcp.WithString("name",
				mcp.Description("Resource name for a specific get (empty to list all)"),
			),
		),
		mcp.NewTool("joe_k8s_logs",
			mcp.WithDescription("Retrieve logs from a Kubernetes pod."),
			mcp.WithString("source_id",
				mcp.Description("The Kubernetes source ID from Joe's source registry"),
				mcp.Required(),
			),
			mcp.WithString("namespace",
				mcp.Description("Kubernetes namespace"),
				mcp.Required(),
			),
			mcp.WithString("pod",
				mcp.Description("Pod name"),
				mcp.Required(),
			),
			mcp.WithString("container",
				mcp.Description("Container name (optional, defaults to first container)"),
			),
			mcp.WithNumber("tail",
				mcp.Description("Number of log lines to return (default 100)"),
				mcp.DefaultNumber(100),
			),
		),
		mcp.NewTool("joe_metrics_query",
			mcp.WithDescription("Execute a PromQL metrics query against a connected Prometheus/Mimir source."),
			mcp.WithString("source_id",
				mcp.Description("The Prometheus source ID from Joe's source registry"),
				mcp.Required(),
			),
			mcp.WithString("query",
				mcp.Description("PromQL query (e.g. 'rate(http_requests_total[5m])')"),
				mcp.Required(),
			),
		),
		mcp.NewTool("joe_logs_search",
			mcp.WithDescription("Search logs using LogQL against a connected Loki source."),
			mcp.WithString("source_id",
				mcp.Description("The Loki source ID from Joe's source registry"),
				mcp.Required(),
			),
			mcp.WithString("query",
				mcp.Description("LogQL query (e.g. '{app=\"payment-svc\"} |= \"error\"')"),
				mcp.Required(),
			),
			mcp.WithNumber("limit",
				mcp.Description("Maximum number of log entries to return (default 100)"),
				mcp.DefaultNumber(100),
			),
			mcp.WithNumber("since_seconds",
				mcp.Description("Look back this many seconds from now (default 3600 = 1 hour)"),
				mcp.DefaultNumber(3600),
			),
		),
		mcp.NewTool("joe_knowledge_search",
			mcp.WithDescription("Semantic search over Joe's knowledge store — runbooks, wiki pages, and learned operational patterns."),
			mcp.WithString("query",
				mcp.Description("Natural language query (e.g. 'payment service database connection errors')"),
				mcp.Required(),
			),
			mcp.WithNumber("top_k",
				mcp.Description("Maximum number of results to return (default 5)"),
				mcp.DefaultNumber(5),
			),
		),
		mcp.NewTool("joe_incidents",
			mcp.WithDescription("List active incidents and alerts from a connected alerting source (Alertmanager or PagerDuty)."),
			mcp.WithString("source_id",
				mcp.Description("The alerting source ID from Joe's source registry"),
				mcp.Required(),
			),
			mcp.WithString("filter",
				mcp.Description("Optional filter string (e.g. 'severity=critical' for Alertmanager or service ID for PagerDuty)"),
			),
		),
	}
}
