-- Documentation proposals: draft updates generated by Joe and pending human approval
CREATE TABLE doc_proposals (
    id TEXT PRIMARY KEY,
    title TEXT NOT NULL,
    target_type TEXT NOT NULL,   -- confluence | notion | git
    target_id TEXT NOT NULL,     -- page ID or file path
    target_url TEXT,
    current_content TEXT,        -- fetched at draft time
    proposed_content TEXT NOT NULL,
    diff TEXT,                   -- unified diff (pre-computed)
    status TEXT NOT NULL DEFAULT 'pending',
                                 -- pending | approved | published | rejected
    context TEXT,
    knowledge_entry_ids TEXT,    -- JSON array of entry IDs used
    rejected_reason TEXT,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    approved_at DATETIME,
    published_at DATETIME
);

CREATE INDEX idx_proposals_status ON doc_proposals(status);
CREATE INDEX idx_proposals_target ON doc_proposals(target_type, target_id);
