// Package proposals manages documentation update proposals generated by Joe.
// A proposal represents a draft doc update awaiting human approval before
// being published back to Confluence, Notion, or a Git repository.
package proposals

import (
	"errors"
	"time"
)

// ErrNotFound is the sentinel for a proposal lookup that matched no row. The
// repository wraps it with the offending id (fmt.Errorf("%w: ...")), so callers
// can distinguish a genuinely missing proposal (errors.Is → HTTP 404) from a
// real store failure (→ 500) instead of masking every error as not-found.
var ErrNotFound = errors.New("proposal not found")

// ProposalStatus represents the lifecycle state of a proposal.
type ProposalStatus string

const (
	StatusPending   ProposalStatus = "pending"
	StatusApproved  ProposalStatus = "approved"
	StatusPublished ProposalStatus = "published"
	StatusRejected  ProposalStatus = "rejected"
)

// TargetType identifies the external system a proposal targets.
type TargetType string

const (
	TargetConfluence TargetType = "confluence"
	TargetNotion     TargetType = "notion"
	TargetGit        TargetType = "git"
)

// Proposal is a documentation update draft generated by Joe.
type Proposal struct {
	ID                string         `json:"id"`
	Title             string         `json:"title"`
	TargetType        TargetType     `json:"target_type"`
	TargetID          string         `json:"target_id"`
	TargetURL         string         `json:"target_url,omitempty"`
	CurrentContent    string         `json:"current_content,omitempty"`
	ProposedContent   string         `json:"proposed_content"`
	Diff              string         `json:"diff,omitempty"`
	Status            ProposalStatus `json:"status"`
	Context           string         `json:"context,omitempty"`
	KnowledgeEntryIDs []string       `json:"knowledge_entry_ids,omitempty"`
	RejectedReason    string         `json:"rejected_reason,omitempty"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
	ApprovedAt        *time.Time     `json:"approved_at,omitempty"`
	PublishedAt       *time.Time     `json:"published_at,omitempty"`
}
